### PR TITLE
[REG-428] update rgbot version

### PR DESCRIPTION
**Pull request by RG-nAmKcAz**

### CODE REVIEW

**Review by abeizer — APPROVED** [review]

**Review by abeizer — CHANGES_REQUESTED** [review]
Approved then realized we check in package-lock. Probably want to run npm install

**Comment by abeizer** [comment]
(Same for the other templates)

**Comment by RG-nAmKcAz** [comment]
how about we delete package-lock instead

**Comment by abeizer** [comment]
> how about we delete package-lock instead

I hate that thing, get it out of here

**Comment by RG-nAmKcAz** [comment]
i updated it instead for now because .. reasons.. anyway

**Comment by RG-nAmKcAz** [comment]
now you has me blocked

**Review by abeizer — APPROVED** [review]

**Pull request merged**
